### ISSUE TITLE
How can I test two apk communicating on one device just like AIDL

### ISSUE THREAD

**Issue by bingxuebage** [nkh-lab/ndk-vsomeip-hello-world#1]
I want to replace AIDL with vsomeip to do RPC ，
but I found vsomeip can only use thread  communication or two device app communication ，
Is there any examples of apks communicating with each other

Thank you, God

**Comment by nkh-lab** [comment]
Hi,
No such example on my GiHub.

**Comment by bingxuebage** [comment]
thanks sir!
i. find the way ,because vsome use boost base on Aio
but android use selinux ; 

so make two apk as  the same   “VSOMEIP_BASE_PATH” & “VSOMEIP_CONFIGURATION” config
and make. two apk has permision read and wirte "VSOMEIP_BASE_PATH"

the two apk can  communite with each other base aio (file) not the true net

**vsomeip can replace  aidl do native rpc like dbus!**
